import type {PronunciationGroup} from "@flashcards/content/korean/pronunciation/types/PronunciationGroup";

/**
 * The sound changes of Korean, each with words that show it, in the order they are taught. The words and the explanations are our
 * own; the rules and the pronunciations follow the standard pronunciation rules (표준 발음법, National Institute of Korean Language),
 * checked against `koroman` in the test. The rows deserve a check by a Korean reader.
 */
export const PRONUNCIATION_GROUPS: readonly PronunciationGroup[] = [
  {
    rule: "Aspiration",
    explanation:
      "ㅎ next to ㄱ, ㄷ, ㅂ or ㅈ blends with it into the breathy ㅋ, ㅌ, ㅍ or ㅊ, whichever side the ㅎ is on.",
    words: [
      {id: "ko-pronunciation-jota", word: "좋다", said: "조타", romanisation: "jota", translation: "to be good"},
      {id: "ko-pronunciation-noko", word: "놓고", said: "노코", romanisation: "noko", translation: "to put down and"},
      {id: "ko-pronunciation-eotteoke", word: "어떻게", said: "어떠케", romanisation: "eotteoke", translation: "how"},
      {
        id: "ko-pronunciation-geureochi",
        word: "그렇지",
        said: "그러치",
        romanisation: "geureochi",
        translation: "that's right",
      },
      {id: "ko-pronunciation-ipak", word: "입학", said: "이팍", romanisation: "ipak", translation: "school admission"},
      {id: "ko-pronunciation-chuka", word: "축하", said: "추카", romanisation: "chuka", translation: "congratulations"},
      {id: "ko-pronunciation-manta", word: "많다", said: "만타", romanisation: "manta", translation: "to be many"},
      {id: "ko-pronunciation-nata", word: "낳다", said: "나타", romanisation: "nata", translation: "to give birth"},
    ],
  },
  {
    rule: "Liaison",
    explanation:
      "A final consonant followed by a vowel moves across to start the next syllable. The ㅇ that starts that syllable is silent.",
    words: [
      {id: "ko-pronunciation-eumak", word: "음악", said: "으막", romanisation: "eumak", translation: "music"},
      {
        id: "ko-pronunciation-hangugeo",
        word: "한국어",
        said: "한구거",
        romanisation: "hangugeo",
        translation: "Korean language",
      },
      {id: "ko-pronunciation-ilgeoyo", word: "읽어요", said: "일거요", romanisation: "ilgeoyo", translation: "read"},
      {id: "ko-pronunciation-meogeoyo", word: "먹어요", said: "머거요", romanisation: "meogeoyo", translation: "eat"},
      {id: "ko-pronunciation-kkochi", word: "꽃이", said: "꼬치", romanisation: "kkochi", translation: "the flower"},
      {id: "ko-pronunciation-anjayo", word: "앉아요", said: "안자요", romanisation: "anjayo", translation: "sit"},
      {id: "ko-pronunciation-osi", word: "옷이", said: "오시", romanisation: "osi", translation: "the clothes"},
      {id: "ko-pronunciation-sibo", word: "십오", said: "시보", romanisation: "sibo", translation: "fifteen"},
    ],
  },
  {
    rule: "Nasalisation",
    explanation: "Before ㄴ or ㅁ, a final that sounds like ㄱ, ㄷ or ㅂ becomes ㅇ, ㄴ or ㅁ.",
    words: [
      {
        id: "ko-pronunciation-hangungmal",
        word: "한국말",
        said: "한궁말",
        romanisation: "hangungmal",
        translation: "Korean speech",
      },
      {id: "ko-pronunciation-hamnida", word: "합니다", said: "함니다", romanisation: "hamnida", translation: "do"},
      {id: "ko-pronunciation-meongneun", word: "먹는", said: "멍는", romanisation: "meongneun", translation: "eating"},
      {
        id: "ko-pronunciation-simman",
        word: "십만",
        said: "심만",
        romanisation: "simman",
        translation: "one hundred thousand",
      },
      {
        id: "ko-pronunciation-jangnyeon",
        word: "작년",
        said: "장년",
        romanisation: "jangnyeon",
        translation: "last year",
      },
      {id: "ko-pronunciation-danneun", word: "닫는", said: "단는", romanisation: "danneun", translation: "closing"},
      {id: "ko-pronunciation-ammun", word: "앞문", said: "암문", romanisation: "ammun", translation: "front door"},
      {id: "ko-pronunciation-binmul", word: "빗물", said: "빈물", romanisation: "binmul", translation: "rainwater"},
    ],
  },
  {
    rule: "ㄴ and ㄹ",
    explanation: "ㄴ beside ㄹ becomes ㄹ, so 신라 is said 실라.",
    words: [
      {id: "ko-pronunciation-silla", word: "신라", said: "실라", romanisation: "silla", translation: "Silla"},
      {id: "ko-pronunciation-pyeolli", word: "편리", said: "펼리", romanisation: "pyeolli", translation: "convenience"},
      {id: "ko-pronunciation-yeollak", word: "연락", said: "열락", romanisation: "yeollak", translation: "contact"},
      {
        id: "ko-pronunciation-seollal",
        word: "설날",
        said: "설랄",
        romanisation: "seollal",
        translation: "Lunar New Year",
      },
      {id: "ko-pronunciation-kallal", word: "칼날", said: "칼랄", romanisation: "kallal", translation: "knife blade"},
      {id: "ko-pronunciation-sillae", word: "실내", said: "실래", romanisation: "sillae", translation: "indoors"},
    ],
  },
  {
    rule: "ㄹ after other finals",
    explanation: "After any final except ㄹ, a ㄹ is said as ㄴ, and a final ㄱ or ㅂ before it becomes ㅇ or ㅁ.",
    words: [
      {id: "ko-pronunciation-jongno", word: "종로", said: "종노", romanisation: "jongno", translation: "Jongno"},
      {id: "ko-pronunciation-simni", word: "심리", said: "심니", romanisation: "simni", translation: "psychology"},
      {
        id: "ko-pronunciation-jeongni",
        word: "정리",
        said: "정니",
        romanisation: "jeongni",
        translation: "organisation",
      },
      {id: "ko-pronunciation-chimnyak", word: "침략", said: "침냑", romanisation: "chimnyak", translation: "invasion"},
      {
        id: "ko-pronunciation-hyeomnyeok",
        word: "협력",
        said: "혐녁",
        romanisation: "hyeomnyeok",
        translation: "cooperation",
      },
      {
        id: "ko-pronunciation-daetongnyeong",
        word: "대통령",
        said: "대통녕",
        romanisation: "daetongnyeong",
        translation: "president",
      },
    ],
  },
  {
    rule: "Tensing",
    explanation:
      "After a final that sounds like ㄱ, ㄷ or ㅂ, the next ㄱ, ㄷ, ㅂ, ㅅ or ㅈ is said tense (ㄲ, ㄸ, ㅃ, ㅆ, ㅉ). So is the ending after a verb stem ending in ㄴ or ㅁ (신다, 앉다). The spelling does not show it.",
    words: [
      {id: "ko-pronunciation-hakgyo", word: "학교", said: "학꾜", romanisation: "hakgyo", translation: "school"},
      {id: "ko-pronunciation-meokda", word: "먹다", said: "먹따", romanisation: "meokda", translation: "to eat"},
      {id: "ko-pronunciation-gukbap", word: "국밥", said: "국빱", romanisation: "gukbap", translation: "rice soup"},
      {
        id: "ko-pronunciation-bapsang",
        word: "밥상",
        said: "밥쌍",
        romanisation: "bapsang",
        translation: "dining table",
      },
      {id: "ko-pronunciation-itda", word: "있다", said: "읻따", romanisation: "itda", translation: "to exist"},
      {
        id: "ko-pronunciation-gapjagi",
        word: "갑자기",
        said: "갑짜기",
        romanisation: "gapjagi",
        translation: "suddenly",
      },
      {id: "ko-pronunciation-apgil", word: "앞길", said: "압낄", romanisation: "apgil", translation: "the road ahead"},
      {id: "ko-pronunciation-mitda", word: "믿다", said: "믿따", romanisation: "mitda", translation: "to believe"},
      {id: "ko-pronunciation-haksaeng", word: "학생", said: "학쌩", romanisation: "haksaeng", translation: "student"},
      {id: "ko-pronunciation-deutgo", word: "듣고", said: "듣꼬", romanisation: "deutgo", translation: "to listen and"},
      {id: "ko-pronunciation-japda", word: "잡다", said: "잡따", romanisation: "japda", translation: "to catch"},
      {id: "ko-pronunciation-anda", word: "앉다", said: "안따", romanisation: "anda", translation: "to sit"},
      {
        id: "ko-pronunciation-sinda",
        word: "신다",
        said: "신따",
        romanisation: "sinda",
        translation: "to wear footwear",
      },
    ],
  },
  {
    rule: "Palatalisation",
    explanation: "A final ㄷ or ㅌ followed by 이 is said ㅈ or ㅊ, so 같이 is said 가치.",
    words: [
      {id: "ko-pronunciation-gachi", word: "같이", said: "가치", romanisation: "gachi", translation: "together"},
      {id: "ko-pronunciation-guji", word: "굳이", said: "구지", romanisation: "guji", translation: "necessarily"},
      {id: "ko-pronunciation-haedoji", word: "해돋이", said: "해도지", romanisation: "haedoji", translation: "sunrise"},
      {id: "ko-pronunciation-maji", word: "맏이", said: "마지", romanisation: "maji", translation: "eldest child"},
      {
        id: "ko-pronunciation-buchida",
        word: "붙이다",
        said: "부치다",
        romanisation: "buchida",
        translation: "to attach",
      },
      {id: "ko-pronunciation-kkeuchi", word: "끝이", said: "끄치", romanisation: "kkeuchi", translation: "the end"},
    ],
  },
  {
    rule: "Weak ㅎ",
    explanation: "ㅎ is silent or nearly so after a vowel, ㄴ, ㄹ, ㅁ or ㅇ, and a final ㅎ vanishes before a vowel.",
    words: [
      {id: "ko-pronunciation-joayo", word: "좋아요", said: "조아요", romanisation: "joayo", translation: "is good"},
      {
        id: "ko-pronunciation-gwaenchanayo",
        word: "괜찮아요",
        said: "괜차나요",
        romanisation: "gwaenchanayo",
        translation: "is all right",
      },
      {id: "ko-pronunciation-sireoyo", word: "싫어요", said: "시러요", romanisation: "sireoyo", translation: "dislike"},
      {id: "ko-pronunciation-manayo", word: "많아요", said: "마나요", romanisation: "manayo", translation: "are many"},
    ],
  },
  {
    rule: "Final sounds",
    explanation:
      "At the end of a word, or before a consonant, a final is one of seven sounds: ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ or ㅇ. ㅋ and ㄲ say ㄱ; ㅅ, ㅆ, ㅈ, ㅊ, ㅌ and ㅎ say ㄷ; ㅍ says ㅂ.",
    words: [
      {id: "ko-pronunciation-bueok", word: "부엌", said: "부억", romanisation: "bueok", translation: "kitchen"},
      {id: "ko-pronunciation-kkot", word: "꽃", said: "꼳", romanisation: "kkot", translation: "flower"},
      {id: "ko-pronunciation-ot", word: "옷", said: "옫", romanisation: "ot", translation: "clothes"},
      {id: "ko-pronunciation-bak", word: "밖", said: "박", romanisation: "bak", translation: "outside"},
      {id: "ko-pronunciation-nat", word: "낮", said: "낟", romanisation: "nat", translation: "daytime"},
      {id: "ko-pronunciation-ap", word: "앞", said: "압", romanisation: "ap", translation: "front"},
      {id: "ko-pronunciation-sup", word: "숲", said: "숩", romanisation: "sup", translation: "forest"},
      {id: "ko-pronunciation-bit", word: "빛", said: "빋", romanisation: "bit", translation: "light"},
    ],
  },
  {
    rule: "Two finals",
    explanation:
      "Only one of two final consonants is said: usually the first (넓다 is 널따, 값 is 갑), but ㄺ, ㄻ and ㄿ keep the second (닭 is 닥, 삶 is 삼).",
    words: [
      {id: "ko-pronunciation-gap", word: "값", said: "갑", romanisation: "gap", translation: "price"},
      {id: "ko-pronunciation-eopda", word: "없다", said: "업따", romanisation: "eopda", translation: "not to exist"},
      {id: "ko-pronunciation-ikda", word: "읽다", said: "익따", romanisation: "ikda", translation: "to read"},
      {id: "ko-pronunciation-dak", word: "닭", said: "닥", romanisation: "dak", translation: "chicken"},
      {id: "ko-pronunciation-sam", word: "삶", said: "삼", romanisation: "sam", translation: "life"},
      {id: "ko-pronunciation-neolda", word: "넓다", said: "널따", romanisation: "neolda", translation: "to be wide"},
      {id: "ko-pronunciation-yeodeol", word: "여덟", said: "여덜", romanisation: "yeodeol", translation: "eight"},
    ],
  },
  {
    rule: "Added ㄴ",
    explanation:
      "In a compound, or after a prefix, an ㄴ is added when the first part ends in a consonant and the next begins with 이, 야, 여, 요 or 유 (한여름 is said 한녀름). It then spreads as above.",
    words: [
      {
        id: "ko-pronunciation-hannyeoreum",
        word: "한여름",
        said: "한녀름",
        romanisation: "hannyeoreum",
        translation: "midsummer",
      },
      {
        id: "ko-pronunciation-maennip",
        word: "맨입",
        said: "맨닙",
        romanisation: "maennip",
        translation: "an empty mouth",
      },
      {id: "ko-pronunciation-somnibul", word: "솜이불", said: "솜니불", romanisation: "somnibul", translation: "quilt"},
      {id: "ko-pronunciation-damnyo", word: "담요", said: "담뇨", romanisation: "damnyo", translation: "blanket"},
      {
        id: "ko-pronunciation-nunnyogi",
        word: "눈요기",
        said: "눈뇨기",
        romanisation: "nunnyogi",
        translation: "a feast for the eyes",
      },
      {
        id: "ko-pronunciation-saengnyeonpil",
        word: "색연필",
        said: "생년필",
        romanisation: "saengnyeonpil",
        translation: "coloured pencil",
      },
      {
        id: "ko-pronunciation-yeongeomnyong",
        word: "영업용",
        said: "영엄뇽",
        romanisation: "yeongeomnyong",
        translation: "for commercial use",
      },
      {
        id: "ko-pronunciation-kkonnip",
        word: "꽃잎",
        said: "꼰닙",
        romanisation: "kkonnip",
        translation: "flower petal",
      },
      {
        id: "ko-pronunciation-seoullyeok",
        word: "서울역",
        said: "서울력",
        romanisation: "seoullyeok",
        translation: "Seoul Station",
      },
      {
        id: "ko-pronunciation-hwiballyu",
        word: "휘발유",
        said: "휘발류",
        romanisation: "hwiballyu",
        translation: "petrol",
      },
    ],
  },
];
