import type {Kana} from "@flashcards/content/japanese/Kana";

/** The 33 combinations of an i-row kana with a small ya, yu or yo, read as one syllable. */
export const COMBINED_KANA: readonly Kana[] = [
  {romaji: "kya", hiragana: "きゃ", katakana: "キャ"},
  {romaji: "kyu", hiragana: "きゅ", katakana: "キュ"},
  {romaji: "kyo", hiragana: "きょ", katakana: "キョ"},
  {romaji: "sha", hiragana: "しゃ", katakana: "シャ"},
  {romaji: "shu", hiragana: "しゅ", katakana: "シュ"},
  {romaji: "sho", hiragana: "しょ", katakana: "ショ"},
  {romaji: "cha", hiragana: "ちゃ", katakana: "チャ"},
  {romaji: "chu", hiragana: "ちゅ", katakana: "チュ"},
  {romaji: "cho", hiragana: "ちょ", katakana: "チョ"},
  {romaji: "nya", hiragana: "にゃ", katakana: "ニャ"},
  {romaji: "nyu", hiragana: "にゅ", katakana: "ニュ"},
  {romaji: "nyo", hiragana: "にょ", katakana: "ニョ"},
  {romaji: "hya", hiragana: "ひゃ", katakana: "ヒャ"},
  {romaji: "hyu", hiragana: "ひゅ", katakana: "ヒュ"},
  {romaji: "hyo", hiragana: "ひょ", katakana: "ヒョ"},
  {romaji: "mya", hiragana: "みゃ", katakana: "ミャ"},
  {romaji: "myu", hiragana: "みゅ", katakana: "ミュ"},
  {romaji: "myo", hiragana: "みょ", katakana: "ミョ"},
  {romaji: "rya", hiragana: "りゃ", katakana: "リャ"},
  {romaji: "ryu", hiragana: "りゅ", katakana: "リュ"},
  {romaji: "ryo", hiragana: "りょ", katakana: "リョ"},
  {romaji: "gya", hiragana: "ぎゃ", katakana: "ギャ"},
  {romaji: "gyu", hiragana: "ぎゅ", katakana: "ギュ"},
  {romaji: "gyo", hiragana: "ぎょ", katakana: "ギョ"},
  {romaji: "ja", hiragana: "じゃ", katakana: "ジャ"},
  {romaji: "ju", hiragana: "じゅ", katakana: "ジュ"},
  {romaji: "jo", hiragana: "じょ", katakana: "ジョ"},
  {romaji: "bya", hiragana: "びゃ", katakana: "ビャ"},
  {romaji: "byu", hiragana: "びゅ", katakana: "ビュ"},
  {romaji: "byo", hiragana: "びょ", katakana: "ビョ"},
  {romaji: "pya", hiragana: "ぴゃ", katakana: "ピャ"},
  {romaji: "pyu", hiragana: "ぴゅ", katakana: "ピュ"},
  {romaji: "pyo", hiragana: "ぴょ", katakana: "ピョ"},
];
