import type {Kana} from "@flashcards/content/japanese/Kana";

/** The 25 kana written with dakuten or handakuten. ぢ and づ sound as じ and ず, so they take `dji` and `dzu`, as を takes `wo`: each sound on a card names one character. */
export const VOICED_KANA: readonly Kana[] = [
  {romaji: "ga", hiragana: "が", katakana: "ガ"},
  {romaji: "gi", hiragana: "ぎ", katakana: "ギ"},
  {romaji: "gu", hiragana: "ぐ", katakana: "グ"},
  {romaji: "ge", hiragana: "げ", katakana: "ゲ"},
  {romaji: "go", hiragana: "ご", katakana: "ゴ"},
  {romaji: "za", hiragana: "ざ", katakana: "ザ"},
  {romaji: "ji", hiragana: "じ", katakana: "ジ"},
  {romaji: "zu", hiragana: "ず", katakana: "ズ"},
  {romaji: "ze", hiragana: "ぜ", katakana: "ゼ"},
  {romaji: "zo", hiragana: "ぞ", katakana: "ゾ"},
  {romaji: "da", hiragana: "だ", katakana: "ダ"},
  {romaji: "dji", hiragana: "ぢ", katakana: "ヂ"},
  {romaji: "dzu", hiragana: "づ", katakana: "ヅ"},
  {romaji: "de", hiragana: "で", katakana: "デ"},
  {romaji: "do", hiragana: "ど", katakana: "ド"},
  {romaji: "ba", hiragana: "ば", katakana: "バ"},
  {romaji: "bi", hiragana: "び", katakana: "ビ"},
  {romaji: "bu", hiragana: "ぶ", katakana: "ブ"},
  {romaji: "be", hiragana: "べ", katakana: "ベ"},
  {romaji: "bo", hiragana: "ぼ", katakana: "ボ"},
  {romaji: "pa", hiragana: "ぱ", katakana: "パ"},
  {romaji: "pi", hiragana: "ぴ", katakana: "ピ"},
  {romaji: "pu", hiragana: "ぷ", katakana: "プ"},
  {romaji: "pe", hiragana: "ぺ", katakana: "ペ"},
  {romaji: "po", hiragana: "ぽ", katakana: "ポ"},
];
