import type {Deck} from "@flashcards/content/types/Deck";
import type {VocabNote} from "@flashcards/content/types/VocabNote";

function word(slug: string, dutch: string, meaning: string): VocabNote {
  return {id: `nl-vocab-${slug}`, language: "nl", word: dutch, meaning, romanisation: ""};
}

/**
 * A hundred everyday words for a first week of Dutch, two hundred cards once each is learned both ways. Dutch is already in Latin letters, so there is no
 * romanisation to show. The words are ours, chosen for being common, not copied from a list.
 */
export const STARTER_DECK: Deck = {
  id: "nl-starter",
  name: "Dutch starter words",
  language: "nl",
  notes: [
    word("water", "water", "water"),
    word("house", "huis", "house"),
    word("school", "school", "school"),
    word("friend", "vriend", "friend"),
    word("book", "boek", "book"),
    word("time", "tijd", "time"),
    word("person", "persoon", "person"),
    word("man", "man", "man"),
    word("woman", "vrouw", "woman"),
    word("child", "kind", "child"),
    word("name", "naam", "name"),
    word("day", "dag", "day"),
    word("night", "nacht", "night"),
    word("week", "week", "week"),
    word("year", "jaar", "year"),
    word("morning", "ochtend", "morning"),
    word("evening", "avond", "evening"),
    word("city", "stad", "city"),
    word("country", "land", "country"),
    word("street", "straat", "street"),
    word("car", "auto", "car"),
    word("bicycle", "fiets", "bicycle"),
    word("train", "trein", "train"),
    word("bus", "bus", "bus"),
    word("shop", "winkel", "shop"),
    word("work", "werk", "work"),
    word("money", "geld", "money"),
    word("food", "eten", "food"),
    word("bread", "brood", "bread"),
    word("cheese", "kaas", "cheese"),
    word("milk", "melk", "milk"),
    word("coffee", "koffie", "coffee"),
    word("tea", "thee", "tea"),
    word("apple", "appel", "apple"),
    word("egg", "ei", "egg"),
    word("fish", "vis", "fish"),
    word("meat", "vlees", "meat"),
    word("table", "tafel", "table"),
    word("chair", "stoel", "chair"),
    word("door", "deur", "door"),
    word("window", "raam", "window"),
    word("room", "kamer", "room"),
    word("kitchen", "keuken", "kitchen"),
    word("bed", "bed", "bed"),
    word("hand", "hand", "hand"),
    word("head", "hoofd", "head"),
    word("eye", "oog", "eye"),
    word("heart", "hart", "heart"),
    word("mother", "moeder", "mother"),
    word("father", "vader", "father"),
    word("brother", "broer", "brother"),
    word("sister", "zus", "sister"),
    word("dog", "hond", "dog"),
    word("cat", "kat", "cat"),
    word("sun", "zon", "sun"),
    word("rain", "regen", "rain"),
    word("sea", "zee", "sea"),
    word("tree", "boom", "tree"),
    word("flower", "bloem", "flower"),
    word("to-be", "zijn", "to be"),
    word("to-have", "hebben", "to have"),
    word("to-go", "gaan", "to go"),
    word("to-come", "komen", "to come"),
    word("to-do", "doen", "to do, to make"),
    word("to-see", "zien", "to see"),
    word("to-hear", "horen", "to hear"),
    word("to-speak", "spreken", "to speak"),
    word("to-eat", "eten", "to eat"),
    word("to-drink", "drinken", "to drink"),
    word("to-sleep", "slapen", "to sleep"),
    word("to-read", "lezen", "to read"),
    word("to-write", "schrijven", "to write"),
    word("to-want", "willen", "to want"),
    word("to-know", "weten", "to know (a fact)"),
    word("to-live", "wonen", "to live (in a place)"),
    word("to-buy", "kopen", "to buy"),
    word("to-give", "geven", "to give"),
    word("to-take", "nemen", "to take"),
    word("to-learn", "leren", "to learn"),
    word("big", "groot", "big"),
    word("small", "klein", "small"),
    word("good", "goed", "good"),
    word("bad", "slecht", "bad"),
    word("new", "nieuw", "new"),
    word("old", "oud", "old"),
    word("beautiful", "mooi", "beautiful"),
    word("cold", "koud", "cold"),
    word("warm", "warm", "warm"),
    word("expensive", "duur", "expensive"),
    word("hello", "hallo", "hello"),
    word("goodbye", "doei", "bye"),
    word("please", "alsjeblieft", "please, here you are"),
    word("thank-you", "dank je wel", "thank you"),
    word("yes", "ja", "yes"),
    word("no", "nee", "no"),
    word("today", "vandaag", "today"),
    word("tomorrow", "morgen", "tomorrow"),
    word("here", "hier", "here"),
    word("very", "heel", "very"),
    word("also", "ook", "also, too"),
  ],
};
