import {Link} from "react-router";
import {Account} from "@src/react/pages/settings/components/account/Account";
import {DailyGoalSetting} from "@src/react/pages/settings/components/daily-goal-setting/DailyGoalSetting";
import {DeckLimits} from "@src/react/pages/settings/components/deck-limits/DeckLimits";
import {DesiredRetentionSetting} from "@src/react/pages/settings/components/desired-retention-setting/DesiredRetentionSetting";
import {ListenOnlySetting} from "@src/react/pages/settings/components/listen-only-setting/ListenOnlySetting";
import {ROUTES} from "@src/react/routes/Routes";
import {SetAsideWhenStrugglingSetting} from "@src/react/pages/settings/components/set-aside-when-struggling-setting/SetAsideWhenStrugglingSetting";
import {SpeedSetting} from "@src/react/pages/settings/components/speed-setting/SpeedSetting";
import {StrugglingAfterSetting} from "@src/react/pages/settings/components/struggling-after-setting/StrugglingAfterSetting";
import {SuspendedCards} from "@src/react/pages/settings/components/suspended-cards/SuspendedCards";
import {ThemeSetting} from "@src/react/pages/settings/components/theme-setting/ThemeSetting";
import {VoiceSetting} from "@src/react/pages/settings/components/voice-setting/VoiceSetting";

/** How much the learner takes on each day, and how they would like to hear the words. */
export function SettingsPage(): React.JSX.Element {
  return (
    <main data-testid="settings-screen" className="mx-auto flex max-w-xl flex-col gap-6 p-4">
      <h1 className="text-2xl font-semibold">Settings</h1>

      <DailyGoalSetting />

      <DeckLimits />

      <DesiredRetentionSetting />

      <StrugglingAfterSetting />

      <SetAsideWhenStrugglingSetting />

      <VoiceSetting />

      <SpeedSetting />

      <ThemeSetting />

      <ListenOnlySetting />

      <Account />

      <SuspendedCards />

      <p className="text-sm text-ink-muted">
        The voices are synthetic: speech generated by Azure AI Speech, not recorded people.
      </p>

      <Link
        to={ROUTES.home}
        data-testid="close-settings"
        className="rounded-xl bg-accent px-4 py-3 text-center text-lg font-semibold text-ground"
      >
        Done
      </Link>
    </main>
  );
}
