import {BackLink} from "@src/react/components/back-link/BackLink";
import {Link} from "react-router";
import {Account} from "@src/react/pages/settings/components/account/Account";
import {AudioFillSetting} from "@src/react/pages/settings/components/audio-fill-setting/AudioFillSetting";
import {ClearThisDevice} from "@src/react/pages/settings/components/clear-this-device/ClearThisDevice";
import {DailyGoalSetting} from "@src/react/pages/settings/components/daily-goal-setting/DailyGoalSetting";
import {DeckSettings} from "@src/react/pages/settings/components/deck-settings/DeckSettings";
import {DesiredRetentionSetting} from "@src/react/pages/settings/components/desired-retention-setting/DesiredRetentionSetting";
import {ReminderSetting} from "@src/react/pages/settings/components/reminder-setting/ReminderSetting";
import {ROUTES} from "@src/react/routes/Routes";
import {SetAsideWhenStrugglingSetting} from "@src/react/pages/settings/components/set-aside-when-struggling-setting/SetAsideWhenStrugglingSetting";
import {SettingsGroup} from "@src/react/pages/settings/components/settings-group/SettingsGroup";
import {SpeedSetting} from "@src/react/pages/settings/components/speed-setting/SpeedSetting";
import {StrugglingAfterSetting} from "@src/react/pages/settings/components/struggling-after-setting/StrugglingAfterSetting";
import {SuspendedCards} from "@src/react/pages/settings/components/suspended-cards/SuspendedCards";
import {ThemeSetting} from "@src/react/pages/settings/components/theme-setting/ThemeSetting";
import {VoiceSetting} from "@src/react/pages/settings/components/voice-setting/VoiceSetting";

/** How much the learner takes on each day, and how they would like to hear the words. Each kind of setting is a framed group of its own. */
export function SettingsPage(): React.JSX.Element {
  return (
    <main data-testid="settings-screen" className="mx-auto flex max-w-xl flex-col gap-6 p-4">
      <BackLink to={ROUTES.home} testId="back-from-settings" label="Back to the home screen" />

      <h1 className="text-2xl font-semibold">Settings</h1>

      <SettingsGroup title="Daily goal">
        <DailyGoalSetting />

        <ReminderSetting />
      </SettingsGroup>

      <DeckSettings />

      <SettingsGroup title="Remembering">
        <DesiredRetentionSetting />
      </SettingsGroup>

      <SettingsGroup title="Struggling cards">
        <StrugglingAfterSetting />

        <SetAsideWhenStrugglingSetting />
      </SettingsGroup>

      <SettingsGroup title="Voice and speed when browsing">
        <VoiceSetting />

        <SpeedSetting />
      </SettingsGroup>

      <SettingsGroup title="Colours">
        <ThemeSetting />

        <AudioFillSetting />
      </SettingsGroup>

      <Account />

      <ClearThisDevice />

      <SettingsGroup title="Suspended cards">
        <SuspendedCards />
      </SettingsGroup>

      <p className="text-sm text-ink-muted">
        The voices are synthetic: speech generated by Azure AI Speech, not recorded people.
      </p>

      <Link
        to={ROUTES.home}
        data-testid="close-settings"
        className="rounded-xl bg-accent px-4 py-3 text-center text-lg font-semibold text-ground"
      >
        Done
      </Link>
    </main>
  );
}
